[package]
name = "todust"
version = "0.9.1"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]
license = "MIT"
edition = "2018"

[dependencies]
chrono = { version = "0.4.9", features = ["serde"] }
csv = "1.1.1"
failure = "0.1.6"
fs2 = "0.4.3"
glob = "0.3.0"
http = "0.1.19"
lazy_static = "1.4.0"
log = "0.4.8"
prettytable-rs = "0.8.0"
serde = "1.0.102"
serde_derive = "1.0.102"
serde_json = "1.0.41"
simplelog = "0.7.4"
structopt = "0.3.4"
tempfile = "3.1.0"
tera = "0.11.20"
text_io = "0.1.7"
tide = "0.3.0"
time = "0.1.42"
toml = "0.5.5"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
xdg = "2.2.0"

[profile.release]
lto = true
