[package]
name = "todust"
version = "0.8.1"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]
license = "MIT"
edition = "2018"

[dependencies]
csv = "1"
failure = "0.1"
glob = "0.2"
lazy_static = "1"
log = "0.4"
prettytable-rs = "0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
simplelog = "0.5"
structopt = "0.2"
tempfile = "3"
tera = "0.11"
text_io = "0.1"
time = "0.1"
xdg = "2"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.7"

[dependencies.rusqlite]
features = ["chrono"]
version = "0.16"

[profile.release]
lto = true
