[package]
name = "todust"
version = "0.5.0"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]
license = "MIT"

[dependencies]
csv = "1"
failure = "0.1"
log = "0.4"
prettytable-rs = "0.7"
serde = "1"
serde_derive = "1"
simplelog = "0.5"
tempfile = "3"
text_io = "0.1"
time = "0.1"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.6"

[dependencies.clap]
features = ["yaml"]
version = "2"

[dependencies.rusqlite]
features = ["chrono"]
version = "0.13"
