:toc: right
:toclevels: 3
:sectanchors:
:sectlink:
:icons: font
:linkattrs:
:numbered:
:idprefix:
:idseparator: -
:doctype: book
:source-highlighter: pygments
:listing-caption: Listing
:hide-uri-scheme:

= Todos


== Active

=== Roman Alekseev15:48Hey man, are you a duty manager

UUID:: c5de9112-6e51-4f9f-812a-3f9e5ca4a240
Started:: 2018-03-07 20:00:30.448779856 UTC

====

Roman Alekseev15:48







Hey man, are you a duty manager today?



Roman Alekseev16:20

Now, when I know it :smile: I’d like to ask you to check again psp entries but on stage for this time:



----

accounts_psp_payment_key: _secret_password_accounts_psp_payment_key

    accounts_psp_payment_secret: _secret_password_accounts_psp_payment_secret

    accounts_psp_payment_passphrase: _secret_password_accounts_psp_payment_passphrase

----

====

=== Axel Barbier10:33yodo you have 5mnsmall call ?I re

UUID:: 89f2dc59-29a7-4b7d-9425-309829c791b1
Started:: 2018-03-07 20:01:00.080076978 UTC

====

Axel Barbier10:33

yo

do you have 5mn

small call ?

I really need that we do something for that: http://git.trivago.trv/projects/DCO/repos/saltstack/pull-requests/539/overview

====

=== www3-sfo und bulkdb2-sfo lüfter tauschen ticket gi

UUID:: 0f372053-23aa-41e7-b297-c6799c53e503
Started:: 2018-03-07 20:01:20.895683161 UTC

====

www3-sfo und bulkdb2-sfo lüfter tauschen ticket gibts nachgucken

====

=== ssl certshsi lbpsp lbprodci https java

UUID:: 9a367e9c-73f6-4faa-b8e4-9b0e0308e24b
Started:: 2018-03-07 20:01:28.017702652 UTC

====

ssl certs



hsi lb

psp lb



prodci https java

====

== Done

=== Achchuthan Ganeshanathan10:05goood morning mancoul

UUID:: 6abb33ca-11d3-4408-a6c9-b1e97acc305d
Started:: 2018-03-07 15:01:14.211795980 UTC
Finished:: 2018-03-07 21:01:14.211795980 UTC

====

Achchuthan Ganeshanathan10:05

goood morning man

could you maybe take a look at this for me https://tasks.trivago.com/browse/RM-10304

when you have a moment

would really help our intern if she has access to the db

====


