:toc: right
:toclevels: 3
:sectanchors:
:sectlink:
:icons: font
:linkattrs:
:numbered:
:idprefix:
:idseparator: -
:doctype: book
:source-highlighter: pygments
:listing-caption: Listing
:hide-uri-scheme:

= Todos

{% if active is defined -%}
== Active
{% for project, entries in active -%}
=== {{ project }}
{% for entry in entries -%}
==== {{ entry.text | single_line | truncate(length=100) }}
Project:: {{ entry.metadata.project }}
UUID:: {{ entry.metadata.uuid }}
Last Change:: {{ entry.metadata.last_change }}
Started:: {{ entry.metadata.started }}
Active Duration:: {{ entry.metadata.started | format_duration_since }}
{% if entry.metadata.due is some %}
Due:: {{ entry.metadata.due }}
{% endif %}

====
{{ entry.text | lines | trim }}
====

{% endfor -%}
{% endfor -%}
{% endif -%}

{% if done is defined -%}
== Done
{% for project, entries in done -%}
=== {{ project }}
{% for entry in entries -%}
==== {{ entry.text | single_line | truncate(length=100) }}
Project:: {{ entry.metadata.project }}
UUID:: {{ entry.metadata.uuid }}
Last Change:: {{ entry.metadata.last_change }}
Started:: {{ entry.metadata.started }}
{% if entry.metadata.due is some %}
Due:: {{ entry.metadata.due }}
{% endif %}

====
{{ entry.text | lines | trim }}
====

{% endfor -%}
{% endfor -%}
{% endif -%}
